"use client"

import { motion } from "framer-motion"

export default function TermsOfService() {
  return (
    <main className="min-h-screen px-6 py-32">
      <div className="max-w-4xl mx-auto">

        <motion.h1
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          className="text-5xl font-semibold mb-10"
        >
          Terms of Service
        </motion.h1>

        <div className="space-y-6 text-muted-foreground leading-relaxed">

          <p>
            By using TRUTHLENS.AI you agree to these terms of service.
          </p>

          <h2 className="text-xl text-foreground font-semibold">
            Acceptable Use
          </h2>

          <p>
            The platform may be used for research, educational, and
            informational purposes related to detecting manipulated media.
          </p>

          <h2 className="text-xl text-foreground font-semibold">
            No Warranty
          </h2>

          <p>
            TRUTHLENS.AI is provided as a research prototype and accuracy of
            deepfake detection results cannot be guaranteed.
          </p>

          <h2 className="text-xl text-foreground font-semibold">
            Limitation of Liability
          </h2>

          <p>
            The developers of TRUTHLENS.AI shall not be held responsible for
            decisions made based on detection results generated by the system.
          </p>

        </div>

      </div>
    </main>
  )
}
